name: Build Cloud Flatpak
on: [push, workflow_dispatch]

jobs:
  flatpak:
    name: "Flatpak Packaging"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Install Flatpak Runtimes & Build Bundle
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: skystream.flatpak
        manifest-path: org.akashdh11.skystream.json
        cache: false
        run-tests: false

    - name: Upload Finished App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: SkyStream-Flatpak-Bundle
        path: skystream.flatpak
